-- Seed: system prompt presets (≥20 covering 4 task types).
-- Run after 001_init_canvas_schema.sql. Idempotent on (scope, task_type, title).

BEGIN;

INSERT INTO canvas.prompt_presets (scope, task_type, title, content, tags, sort_order)
VALUES
  ('system', 'gen.text', '改写为更书面化的中文',
    '[{"role":"system","text":"你是一名资深中文编辑。把用户输入的文本改写为正式书面表达，保持原意，不增删核心信息。"}]'::jsonb,
    ARRAY['rewrite','zh']::text[], 10),
  ('system', 'gen.text', '把段落总结为 3 个要点',
    '[{"role":"system","text":"请用 3 个不超过 30 字的要点概括用户输入的段落，输出 Markdown 列表。"}]'::jsonb,
    ARRAY['summary']::text[], 11),
  ('system', 'gen.text', '中英互译',
    '[{"role":"system","text":"自动判断语种并互译。中文译为自然英文、英文译为流畅中文。只输出译文。"}]'::jsonb,
    ARRAY['translate']::text[], 12),
  ('system', 'gen.text', '故事大纲(三幕结构)',
    '[{"role":"system","text":"按三幕剧结构生成故事大纲：开端 / 冲突上升 / 高潮与结局。每幕 4-6 句。"}]'::jsonb,
    ARRAY['story','script']::text[], 13),
  ('system', 'gen.text', '提取人物表',
    '[{"role":"system","text":"从用户提供的故事文本中抽取人物表，输出 JSON 数组：[{name, age, traits[], role_in_story}]。"}]'::jsonb,
    ARRAY['structured','extract']::text[], 14),
  ('system', 'gen.text', '改成更有戏剧张力的台词',
    '[{"role":"system","text":"把用户给的对白改写为更具戏剧张力、能体现角色性格的台词。保留人物名标签。"}]'::jsonb,
    ARRAY['dialogue']::text[], 15),

  ('system', 'gen.image', '电影质感写实人像',
    '[{"role":"system","text":"cinematic photography, soft natural lighting, shallow depth of field, photorealistic skin texture, 35mm film look"}]'::jsonb,
    ARRAY['portrait','realism']::text[], 20),
  ('system', 'gen.image', '日漫赛璐璐风格',
    '[{"role":"system","text":"anime style, cel shading, vibrant flat colors, clean linework, expressive eyes"}]'::jsonb,
    ARRAY['anime']::text[], 21),
  ('system', 'gen.image', '极简平面海报',
    '[{"role":"system","text":"minimalist poster design, large negative space, single hero element, bold sans-serif typography hint, swiss style"}]'::jsonb,
    ARRAY['poster']::text[], 22),
  ('system', 'gen.image', '赛博朋克霓虹城市',
    '[{"role":"system","text":"cyberpunk skyline, neon signs in mandarin, rainy reflective streets, volumetric haze, blade-runner mood"}]'::jsonb,
    ARRAY['cyberpunk']::text[], 23),
  ('system', 'gen.image', '中国古典工笔画',
    '[{"role":"system","text":"中国古典工笔画风格，细腻线描，淡彩晕染，留白构图，绢本质感"}]'::jsonb,
    ARRAY['traditional','zh']::text[], 24),
  ('system', 'gen.image', '产品摄影白底',
    '[{"role":"system","text":"studio product photography, pure white seamless background, soft box lighting from upper-left, sharp focus, e-commerce ready"}]'::jsonb,
    ARRAY['product']::text[], 25),
  ('system', 'gen.image', '吉卜力田园风',
    '[{"role":"system","text":"ghibli-inspired pastoral scene, hand-painted clouds, lush greens, warm afternoon light, gentle storytelling mood"}]'::jsonb,
    ARRAY['anime','landscape']::text[], 26),

  ('system', 'gen.video', '电影级运镜推进',
    '[{"role":"system","text":"smooth dolly-in shot, cinematic 24fps motion blur, anamorphic flare, gradual focal-length change"}]'::jsonb,
    ARRAY['camera-move']::text[], 30),
  ('system', 'gen.video', '人物自然行走 5s',
    '[{"role":"system","text":"natural walking cycle, balanced stride, hair and clothing react to motion, ambient outdoor lighting"}]'::jsonb,
    ARRAY['character-motion']::text[], 31),
  ('system', 'gen.video', '产品 360° 展示',
    '[{"role":"system","text":"360 degree turntable product spin, soft top light, no background distractions, looped seamlessly"}]'::jsonb,
    ARRAY['product']::text[], 32),
  ('system', 'gen.video', '风景航拍',
    '[{"role":"system","text":"slow aerial drone shot over mountains, golden hour, gentle parallax, calm orchestral mood implied"}]'::jsonb,
    ARRAY['landscape']::text[], 33),
  ('system', 'gen.video', '霓虹街道夜景慢速跟拍',
    '[{"role":"system","text":"slow tracking shot down a neon-lit street at night, rainy reflections, occasional pedestrians, bokeh"}]'::jsonb,
    ARRAY['cyberpunk']::text[], 34),

  ('system', 'gen.audio', '商务旁白(中文女声)',
    '[{"role":"system","text":"中文女声，沉稳大气的商务讲解语气，节奏从容，咬字清晰"}]'::jsonb,
    ARRAY['tts','zh']::text[], 40),
  ('system', 'gen.audio', '欢快电子背景音乐',
    '[{"role":"system","text":"upbeat electronic background music, 110bpm, light synth lead, no vocals, suitable for product reveal"}]'::jsonb,
    ARRAY['bgm']::text[], 41),
  ('system', 'gen.audio', '电影紧张氛围铺底',
    '[{"role":"system","text":"cinematic tension underscore, low drones, sparse cello pulses, building toward subtle crescendo"}]'::jsonb,
    ARRAY['bgm','cinematic']::text[], 42),
  ('system', 'gen.audio', '播客式开场白',
    '[{"role":"system","text":"中文男声，轻松好奇的播客主持口吻，前 3 秒留出短暂留白以便加片头音效"}]'::jsonb,
    ARRAY['tts','podcast']::text[], 43)
ON CONFLICT DO NOTHING;

COMMIT;
