import { Column, CreateDateColumn, Entity, Index, PrimaryColumn } from 'typeorm';

/**
 * ops.request_logs — one row per outbound vendor-API request.
 * Lives in its own `ops` schema (high volume, retention-cleaned, no FKs).
 * The PK `id` IS the request id surfaced to users on error.
 * Secrets are never written here — credentials by label/id only.
 */
@Entity({ schema: 'ops', name: 'request_logs' })
export class RequestLog {
  /** Request id (generated by the caller at request start so it can be returned on error). */
  @PrimaryColumn({ type: 'uuid' })
  id: string;

  @CreateDateColumn({ type: 'timestamptz' })
  created_at: Date;

  @Column({ type: 'timestamptz', nullable: true })
  finished_at: Date | null;

  // ---- dimensions ----
  @Column({ type: 'varchar', length: 20, default: 'invoke' })
  source: string;

  @Column({ type: 'varchar', length: 60, nullable: true })
  operation: string | null;

  @Index()
  @Column({ type: 'uuid', nullable: true })
  owner_id: string | null;

  @Column({ type: 'uuid', nullable: true })
  workspace_id: string | null;

  @Column({ type: 'uuid', nullable: true })
  project_id: string | null;

  // varchar (not uuid): invoke task_id can be a synthetic string (e.g. agent turns), not only a canvas.tasks UUID.
  @Index()
  @Column({ type: 'varchar', length: 120, nullable: true })
  task_id: string | null;

  @Column({ type: 'uuid', nullable: true })
  conversation_id: string | null;

  @Column({ type: 'varchar', length: 60, nullable: true })
  provider_slug: string | null;

  @Column({ type: 'varchar', length: 120, nullable: true })
  model_id: string | null;

  @Column({ type: 'varchar', length: 60, nullable: true })
  adapter_key: string | null;

  @Column({ type: 'uuid', nullable: true })
  channel_id: string | null;

  @Column({ type: 'uuid', nullable: true })
  credential_id: string | null;

  @Column({ type: 'varchar', length: 200, nullable: true })
  credential_label: string | null;

  // ---- outcome ----
  @Column({ type: 'varchar', length: 20, default: 'pending' })
  status: string;

  @Column({ type: 'int', nullable: true })
  http_status: number | null;

  @Column({ type: 'int', nullable: true })
  latency_ms: number | null;

  // ---- detail (sanitized; no secrets) ----
  @Column({ type: 'jsonb', nullable: true })
  request_summary: Record<string, unknown> | null;

  @Column({ type: 'jsonb', nullable: true })
  usage: Record<string, unknown> | null;

  @Column({ type: 'varchar', length: 60, nullable: true })
  error_code: string | null;

  @Column({ type: 'text', nullable: true })
  error_message: string | null;

  @Column({ type: 'jsonb', nullable: true })
  vendor_error: unknown | null;

  @Column({ type: 'jsonb', nullable: true })
  request_body: unknown | null;

  @Column({ type: 'jsonb', nullable: true })
  response_body: unknown | null;

  // ---- billing (frozen at write time from the model's then-current rate) ----
  @Column({ type: 'numeric', precision: 14, scale: 6, nullable: true })
  cost: string | null;

  @Column({ type: 'varchar', length: 10, nullable: true })
  cost_currency: string | null;
}
